#!/usr/bin/env sh


## Set GTK Themes, Icons, Cursor and Fonts

THEME='Catppuccin-Macchiato-Red'
ICONS='Papirus-Dark'
FONT='Fira Code'
CURSOR='Capitaine Cursors (Palenight)'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
