#!/usr/bin/env sh



# Kill already running process
# _ps=(waybar mako mpd polkit-kde-authentication-agent-1 eww)
# for _prs in "${_ps[@]}"; do
# 	if [[ `pidof ${_prs}` ]]; then
# 		killall -9 ${_prs}
# 	fi
# done

# Polkit agent
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Lauch statusbar (waybar)
exec ~/.config/hypr/scripts/statusbar &

# Set wallpaper
swaybg --image /usr/share/backgrounds/current/current.png &

# Apply themes
exec ~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
exec  ~/.config/hypr/scripts/notifications &

# XDG-PORTAL
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# nm-applet
nm-applet --indicator &

# Xwayland
xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2 &

# clipman
wl-paste -t text --watch clipman store &
clipman restore &

# Swaylock
swayidle -w timeout 900 nwg-lock before-sleep nwg-lock &

# Set Cursor Size
# hyprctl setcursor Posy_Cursor_Mono_Black 24 &
hyprctl setcursor "Capitaine-Cursors-Palenight" 24 &

# GTK themes
exec $XDG_CONFIG_HOME/hypr/scripts/gtkthemes &

exec /usr/bin/wlsunset -l 41.8874 -L -87.7656 -t 4500 -T 6500 -g 1.0 &

exec /usr/bin/flatpak run com.discordapp.Discord &
exec /usr/bin/kitty &
exec /usr/bin/flatpak run org.mozilla.Thunderbird &
exec /usr/bin/flatpak run org.mozilla.firefox &
#exec /usr/bin/blueman-applet &
exec /usr/local/bin/piactl connect &
